# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/appscode/jsonpatch"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11.3"
  source = "github.com/pharmer/apimachinery"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.11.3"
  source = "github.com/pharmer/apiserver"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.11.3"

[[override]]
  name = "github.com/openshift/api"
  revision = "31a7bbd2266d178da3c12bb83f5274d387f775e6"

[[override]]
  name = "github.com/openshift/client-go"
  revision = "4688ad28de2e88110c0ea30179c51b9b205f99be"

[[override]]
  name = "github.com/openshift/origin"
  revision = "fecffb2fce100260088a1b9f268c0901a778cf2b"

[[override]]
  branch = "release-branch.go1.9"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v14.6.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.6.2"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/docker/go-connections"
  version = "v0.3.0"

[[override]]
  name = "github.com/docker/go-units"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"

[[override]]
  name = "github.com/docker/libtrust"
  revision = "9cbd2a1374f46905c68a4eb3694a130610adc62a"

[prune]
  go-tests = true
  unused-packages = true
